# Generated by Django 5.1.1 on 2024-11-01 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_question_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_title',
            field=models.CharField(default='TEMP', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('p_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('answers', models.CharField(max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.quiz')),
            ],
        ),
    ]
